"""Ports used by Task Workspace; infrastructure stays behind these boundaries."""

from typing import Protocol
from uuid import UUID


class TaskWorkspaceRepository(Protocol):
    def list_projects(self, member_id: UUID): ...

    def get_project(self, member_id: UUID, project_id: UUID): ...

    def create_project(self, member_id: UUID, name: str, description: str | None): ...

    def update_project(self, member_id: UUID, project_id: UUID, name: str | None, description: str | None): ...

    def delete_project(self, member_id: UUID, project_id: UUID): ...

    def list_statuses(self, member_id: UUID, project_id: UUID): ...

    def create_status(self, member_id: UUID, project_id: UUID, name: str, description: str | None): ...

    def update_status(self, member_id: UUID, project_id: UUID, status_id: UUID, name: str | None, description: str | None, is_completion: bool | None): ...

    def reorder_statuses(self, member_id: UUID, project_id: UUID, status_ids: list[UUID]): ...

    def delete_status(self, member_id: UUID, project_id: UUID, status_id: UUID, reassign_to_status_id: UUID | None): ...

    def project_quota(self, member_id: UUID): ...

    def create_task(self, member_id: UUID, project_id: UUID, name: str, description: str | None, due_date=None, priority: str = "none", label_ids: list[UUID] | None = None, subtasks: list[dict] | None = None): ...

    def update_task(self, member_id: UUID, task_id: UUID, name: str | None, description: str | None, due_date=None, priority: str | None = None, label_ids: list[UUID] | None = None, subtasks: list[dict] | None = None, updated_fields: set[str] | None = None): ...

    def list_tasks(self, member_id: UUID, task_id: UUID | None, project_id: UUID | None, status_id: UUID | None): ...

    def delete_task(self, member_id: UUID, task_id: UUID): ...

    def set_task_status(self, member_id: UUID, task_id: UUID, status_id: UUID): ...

    def move_task_to_status(self, member_id: UUID, task_id: UUID, status_id: UUID): ...

    def task_quota(self, member_id: UUID, project_id: UUID): ...

    def list_labels(self, member_id: UUID): ...

    def create_label(self, member_id: UUID, name: str, color: str | None): ...

    def update_label(self, member_id: UUID, label_id: UUID, name: str | None, color: str | None): ...

    def delete_label(self, member_id: UUID, label_id: UUID): ...

    def set_subtasks(self, member_id: UUID, task_id: UUID, subtasks: list[dict]): ...

    def toggle_subtask(self, member_id: UUID, task_id: UUID, subtask_id: UUID, is_completed: bool): ...

    def get_today(self, member_id: UUID, local_date): ...

    def add_today_task(self, member_id: UUID, task_id: UUID, local_date): ...

    def remove_today_task(self, member_id: UUID, task_id: UUID, local_date): ...

    def reorder_today_tasks(self, member_id: UUID, task_ids: list[UUID], local_date): ...


class TaskWorkspaceStorage(Protocol):
    def delete_task_files(self, task_id: UUID) -> None: ...

    def delete_project_files(self, project_id: UUID) -> None: ...
