"""Ports used by Task Workspace; infrastructure stays behind these boundaries."""

from typing import Protocol
from uuid import UUID


class TaskWorkspaceRepository(Protocol):
    def list_projects(self, member_id: UUID): ...

    def create_project(self, member_id: UUID, name: str, description: str | None): ...

    def update_project(self, member_id: UUID, project_id: UUID, name: str | None, description: str | None): ...

    def delete_project(self, member_id: UUID, project_id: UUID): ...

    def list_statuses(self, member_id: UUID, project_id: UUID): ...

    def create_status(self, member_id: UUID, project_id: UUID, name: str, description: str | None): ...

    def update_status(self, member_id: UUID, project_id: UUID, status_id: UUID, name: str | None, description: str | None): ...

    def delete_status(self, member_id: UUID, project_id: UUID, status_id: UUID): ...

    def create_task(self, member_id: UUID, project_id: UUID, name: str, description: str | None): ...

    def update_task(self, member_id: UUID, task_id: UUID, name: str | None, description: str | None): ...

    def list_tasks(self, member_id: UUID, task_id: UUID | None, project_id: UUID | None, status_id: UUID | None): ...

    def delete_task(self, member_id: UUID, task_id: UUID): ...

    def set_task_status(self, member_id: UUID, task_id: UUID, status_id: UUID): ...

    def move_task_to_status(self, member_id: UUID, task_id: UUID, status_id: UUID): ...


class TaskWorkspaceStorage(Protocol):
    def delete_task_files(self, task_id: UUID) -> None: ...

    def delete_project_files(self, project_id: UUID) -> None: ...
